services:
  redis:
    image: library/redis:7-alpine
    ports:
      - 6381:6381

  postgres:
    # this image is just postgres with pgvector installed
    image: pgvector/pgvector:pg16
    ports:
      - 5437:5437
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: media_development