services:
  redis:
    image: library/redis:7-alpine
    ports:
      - 6379:6379

  postgres:
    # this image is just postgres with pgvector installed
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: media
      POSTGRES_PASSWORD: password
      POSTGRES_DB: media_development