jwt_secret: ENC[AES256_GCM,data:HEmWRpkLstBvb2qnoJsy59MdEDwj+9T6Io/Luhimv/KKq/IutI1XtP3faTj3IAP9c3mw9XGkIOmQ5iNlHVVp6M+0A8Qjpss/mWIgRFZxGHISfxA7tzYbDw==,iv:Jl/C1iG9xoHtQXw0dgV0/GoYV8xCI0IN3naiDXGfdqw=,tag:kNG6EaRKq7tD2/4s4oQGaA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:975050075037:alias/skills-network-team
          created_at: "2025-10-14T14:14:42Z"
          enc: AQICAHgsNGp3OIKeSGQPdfUiu2fSH3Ysp/azRvNg0cWdt1sWAQHoGiZxghhJu5LIqrefZgYWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5/HcgzS1ZhiTBcTcAgEQgDvIbjSvlN+3FTmtss2paUaK4d9XD0gLE8VtqKXjbEsif258nTVox2VwrDryfCxx+XwxFjHsZRTVQ8C7RA==
          aws_profile: skills-network
    lastmodified: "2025-10-14T14:14:43Z"
    mac: ENC[AES256_GCM,data:7KqI9MMrA5Ykq2fM3bPzYT4Cg4t0abprgst2hIxBcA0amKx1BTMjBNwyd/9A0HSaju6u8qiJLucMR0+tb6CeQoiqlE9CCO+f5RSGZuum3DDriYsgOrLsv6PL8LwUg22qIE6WlSQA0o37u4o1QYkU5RD3foHWBWsH4uIpdHLz/X4=,iv:hXjQSvBAH8X+ffGFYp5mKHqtwwvKAO/elo1Ur0JV7rw=,tag:XfX3x1b2bzxXFVGXBUSmYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
